name: Deploy

on:
    push:
        branches:
            - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    services:
    # Start a SonarQube service using Docker
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Wait SonarQube to be ready
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          until curl -s "$SONAR_HOST_URL/api/system/health" | grep -q '"status":"UP"'; do
            echo "Waiting for SonarQube to start..."
            sleep 10
          done
          echo "SonarQube is up and running!"

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
            
      # Optional: Quality Gate check
      # Uncomment the following if you want the job to fail based on Quality Gate status
      # - name: Check SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  deploy:
    name: Publish image in Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/radio-cesarito:latest

      - name: Deploy image
        # Only run this step if the branch is master
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.DEPLOY_HOOK_URL }}
        run: |
            curl "$deploy_url"
