name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
      name: Publish image in Docker Hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/radio-cesarito:latest

        - name: Deploy image
          # Only run this step if the branch is master
          if: github.ref == 'refs/heads/master'
          env:
            deploy_url: ${{ secrets.DEPLOY_HOOK_URL }}
          run: |
            curl "$deploy_url"